# config.yaml

mongodb:
  db_name: "autofinqa_db"
  collection_name: "financial_documents"
  index_name: "vector_index"

astra_db:
  collection_name: "financedata"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 15
  fetch_k: 50
  lambda_mult: 0.5

llm:
  groq:
    provider: "groq"
    # Primary "Smart" Model (Agent & Final Answer)
    model_name: "llama-3.3-70b-versatile"
    
    # Secondary "Fast" Model (Router, Grader, Rewriter)
    # This model has much higher rate limits
    fast_model_name: "llama-3.1-8b-instant" 
    
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048

  openai:
     provider: "openai"
     model_name: "gpt-4o"
     temperature: 0

# Testing and Evaluation Settings
evaluation:
  numeric_threshold: 0.05
  exact_match_tolerance: 1e-6
  metrics:
    - exact_match
    - relative_error
    - threshold_accuracy
  
  dataset_paths:
    dev: "dataset/dev.json"
    test: "dataset/test.json"
    train: "dataset/train.json"