# config.yaml

mongodb:
  db_name: "autofinqa_db"
  collection_name: "financial_documents"
  index_name: "vector_index"

astra_db:
  collection_name: "financedata"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 5
  fetch_k: 20

llm:
  groq:
    provider: "groq"
    # model_name: "openai/gpt-oss-120b"
    model_name: "llama-3.3-70b-versatile"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048

  openai:
     provider: "openai"
     model_name: "gpt-4o"
     temperature: 0


# Testing and Evaluation Settings

evaluation:
  numeric_threshold: 0.05  # 5% relative error tolerance
  exact_match_tolerance: 1e-6
  metrics:
    - exact_match
    - relative_error
    - threshold_accuracy
  
  dataset_paths:
    dev: "dataset/dev.json"
    test: "dataset/test.json"
    train: "dataset/train.json"